// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geifywrqficiuvybmrgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaWZ5d3JxZmljaXV2eWJtcmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTEwNTQsImV4cCI6MjA2MjY4NzA1NH0.s0TvyLL7sdC3P2cWX4HZPzijq6zA9qZ0Ob4whEjrYGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);